# Generated by Django 3.2.7 on 2021-09-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0020_auto_20210801_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
